[package]
name = "dummy-http-server"
version = "0.1.0"
authors = [
    "TNO Software and System Security"
]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.0.29", features = ["derive"] }
